### ISSUE TITLE
need space between quote and citation

### ISSUE THREAD

**Issue by SeanChDavis** [devinsays/better-blockquotes#6]
Editor: http://glui.me/?i=kmtohyflmc2wmgb/2015-11-02_at_11.35_PM.png/
Output: http://glui.me/?i=36z02jwas8zzdol/2015-11-02_at_11.36_PM.png/

**Comment by devinsays** [comment]
Thanks for testing, sorry I never saw a notification for this issue.

I was thinking ideally the theme author would add appropriate styling for the <cite> element so that it displays on a new line (block) or with spacing (inline-block).

I could wrap the `<cite>` element in a `<p>` tag, which would make it always drop to the next the line- but a lot of developers have margins on their p tags which might make that undesirable.

**Comment by SeanChDavis** [comment]
No worries! Shortly after opening this issue, I realized you may have intended for it to output this way. I figured I'd wait to see what your thoughts were. I agree that it could be left as-is and handed over to theme devs to handle that styling. Thanks for getting back!
